AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'pkg/**/*'

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Metrics/AbcSize:
  Max: 40
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 200
Metrics/PerceivedComplexity:
  Max: 10

Style/CommentedKeyword:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/RedundantPercentQ:
  Enabled: false
Style/StringLiterals:
  Enabled: false
