sudo: false
language: ruby
rvm:
  - 2.5.3
  - 2.6.5
  - 2.7.1
before_install: gem install bundler
jobs:
  include:
    - stage: rubocop
      rvm: 2.7.1
      script: rubocop
    - stage: test
      script: rake
